--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Framework.Net.Protobuf.protobuf"
local _M = {}

_M.SIMPLEINT = protobuf.Descriptor();
_M.SIMPLEINT_SIMPLE_FIELD = protobuf.FieldDescriptor();
_M.SIMPLESTRING = protobuf.Descriptor();
_M.SIMPLESTRING_SIMPLE_FIELD = protobuf.FieldDescriptor();

_M.SIMPLEINT_SIMPLE_FIELD.name = "simple"
_M.SIMPLEINT_SIMPLE_FIELD.full_name = ".SimpleInt.simple"
_M.SIMPLEINT_SIMPLE_FIELD.number = 1
_M.SIMPLEINT_SIMPLE_FIELD.index = 0
_M.SIMPLEINT_SIMPLE_FIELD.label = 2
_M.SIMPLEINT_SIMPLE_FIELD.has_default_value = false
_M.SIMPLEINT_SIMPLE_FIELD.default_value = 0
_M.SIMPLEINT_SIMPLE_FIELD.type = 5
_M.SIMPLEINT_SIMPLE_FIELD.cpp_type = 1

_M.SIMPLEINT.name = "SimpleInt"
_M.SIMPLEINT.full_name = ".SimpleInt"
_M.SIMPLEINT.nested_types = {}
_M.SIMPLEINT.enum_types = {}
_M.SIMPLEINT.fields = {_M.SIMPLEINT_SIMPLE_FIELD}
_M.SIMPLEINT.is_extendable = false
_M.SIMPLEINT.extensions = {}
_M.SIMPLESTRING_SIMPLE_FIELD.name = "simple"
_M.SIMPLESTRING_SIMPLE_FIELD.full_name = ".SimpleString.simple"
_M.SIMPLESTRING_SIMPLE_FIELD.number = 1
_M.SIMPLESTRING_SIMPLE_FIELD.index = 0
_M.SIMPLESTRING_SIMPLE_FIELD.label = 2
_M.SIMPLESTRING_SIMPLE_FIELD.has_default_value = false
_M.SIMPLESTRING_SIMPLE_FIELD.default_value = ""
_M.SIMPLESTRING_SIMPLE_FIELD.type = 9
_M.SIMPLESTRING_SIMPLE_FIELD.cpp_type = 9

_M.SIMPLESTRING.name = "SimpleString"
_M.SIMPLESTRING.full_name = ".SimpleString"
_M.SIMPLESTRING.nested_types = {}
_M.SIMPLESTRING.enum_types = {}
_M.SIMPLESTRING.fields = {_M.SIMPLESTRING_SIMPLE_FIELD}
_M.SIMPLESTRING.is_extendable = false
_M.SIMPLESTRING.extensions = {}

_M.SimpleInt = protobuf.Message(_M.SIMPLEINT)
_M.SimpleString = protobuf.Message(_M.SIMPLESTRING)

return _M