--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Framework.Net.Protobuf.protobuf"
local _M = {}

_M.ACCOUNT = protobuf.Descriptor();
_M.ACCOUNT_ID_FIELD = protobuf.FieldDescriptor();
_M.ACCOUNT_NAME_FIELD = protobuf.FieldDescriptor();
_M.ACCOUNT_SEX_FIELD = protobuf.FieldDescriptor();
_M.ACCOUNT_GOLD_FIELD = protobuf.FieldDescriptor();

_M.ACCOUNT_ID_FIELD.name = "id"
_M.ACCOUNT_ID_FIELD.full_name = ".Account.id"
_M.ACCOUNT_ID_FIELD.number = 1
_M.ACCOUNT_ID_FIELD.index = 0
_M.ACCOUNT_ID_FIELD.label = 2
_M.ACCOUNT_ID_FIELD.has_default_value = false
_M.ACCOUNT_ID_FIELD.default_value = 0
_M.ACCOUNT_ID_FIELD.type = 5
_M.ACCOUNT_ID_FIELD.cpp_type = 1

_M.ACCOUNT_NAME_FIELD.name = "name"
_M.ACCOUNT_NAME_FIELD.full_name = ".Account.name"
_M.ACCOUNT_NAME_FIELD.number = 2
_M.ACCOUNT_NAME_FIELD.index = 1
_M.ACCOUNT_NAME_FIELD.label = 2
_M.ACCOUNT_NAME_FIELD.has_default_value = false
_M.ACCOUNT_NAME_FIELD.default_value = ""
_M.ACCOUNT_NAME_FIELD.type = 9
_M.ACCOUNT_NAME_FIELD.cpp_type = 9

_M.ACCOUNT_SEX_FIELD.name = "sex"
_M.ACCOUNT_SEX_FIELD.full_name = ".Account.sex"
_M.ACCOUNT_SEX_FIELD.number = 3
_M.ACCOUNT_SEX_FIELD.index = 2
_M.ACCOUNT_SEX_FIELD.label = 2
_M.ACCOUNT_SEX_FIELD.has_default_value = false
_M.ACCOUNT_SEX_FIELD.default_value = 0
_M.ACCOUNT_SEX_FIELD.type = 5
_M.ACCOUNT_SEX_FIELD.cpp_type = 1

_M.ACCOUNT_GOLD_FIELD.name = "gold"
_M.ACCOUNT_GOLD_FIELD.full_name = ".Account.gold"
_M.ACCOUNT_GOLD_FIELD.number = 4
_M.ACCOUNT_GOLD_FIELD.index = 3
_M.ACCOUNT_GOLD_FIELD.label = 2
_M.ACCOUNT_GOLD_FIELD.has_default_value = false
_M.ACCOUNT_GOLD_FIELD.default_value = 0
_M.ACCOUNT_GOLD_FIELD.type = 5
_M.ACCOUNT_GOLD_FIELD.cpp_type = 1

_M.ACCOUNT.name = "Account"
_M.ACCOUNT.full_name = ".Account"
_M.ACCOUNT.nested_types = {}
_M.ACCOUNT.enum_types = {}
_M.ACCOUNT.fields = {_M.ACCOUNT_ID_FIELD, _M.ACCOUNT_NAME_FIELD, _M.ACCOUNT_SEX_FIELD, _M.ACCOUNT_GOLD_FIELD}
_M.ACCOUNT.is_extendable = false
_M.ACCOUNT.extensions = {}

_M.Account = protobuf.Message(_M.ACCOUNT)

return _M