//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: card.proto
namespace card
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnePlayerCards")]
  public partial class OnePlayerCards : global::ProtoBuf.IExtensible
  {
    public OnePlayerCards() {}
    
    private int _seatid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seatid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seatid
    {
      get { return _seatid; }
      set { _seatid = value; }
    }
    private int _nntype;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nntype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nntype
    {
      get { return _nntype; }
      set { _nntype = value; }
    }
    private int _xgold;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"xgold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int xgold
    {
      get { return _xgold; }
      set { _xgold = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllPlayersCards")]
  public partial class AllPlayersCards : global::ProtoBuf.IExtensible
  {
    public AllPlayersCards() {}
    
    private readonly global::System.Collections.Generic.List<OnePlayerCards> _oneplayercards = new global::System.Collections.Generic.List<OnePlayerCards>();
    [global::ProtoBuf.ProtoMember(1, Name=@"oneplayercards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OnePlayerCards> oneplayercards
    {
      get { return _oneplayercards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}