//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: simpledata.proto
namespace simpledata
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SimpleInt")]
  public partial class SimpleInt : global::ProtoBuf.IExtensible
  {
    public SimpleInt() {}
    
    private int _simple;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"simple", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int simple
    {
      get { return _simple; }
      set { _simple = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SimpleString")]
  public partial class SimpleString : global::ProtoBuf.IExtensible
  {
    public SimpleString() {}
    
    private string _simple;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"simple", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string simple
    {
      get { return _simple; }
      set { _simple = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}