--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Framework.Net.Protobuf.protobuf"
local _M = {}

_M.ACCOUNT = protobuf.Descriptor();
_M.ACCOUNT_ID_FIELD = protobuf.FieldDescriptor();
_M.ACCOUNT_ACC_FIELD = protobuf.FieldDescriptor();
_M.ACCOUNT_PWD_FIELD = protobuf.FieldDescriptor();
_M.ACCOUNT_NICKNAME_FIELD = protobuf.FieldDescriptor();
_M.ACCOUNT_ROOMID_FIELD = protobuf.FieldDescriptor();
_M.ACCOUNT_ICO_FIELD = protobuf.FieldDescriptor();

_M.ACCOUNT_ID_FIELD.name = "id"
_M.ACCOUNT_ID_FIELD.full_name = ".Account.id"
_M.ACCOUNT_ID_FIELD.number = 1
_M.ACCOUNT_ID_FIELD.index = 0
_M.ACCOUNT_ID_FIELD.label = 2
_M.ACCOUNT_ID_FIELD.has_default_value = false
_M.ACCOUNT_ID_FIELD.default_value = 0
_M.ACCOUNT_ID_FIELD.type = 5
_M.ACCOUNT_ID_FIELD.cpp_type = 1

_M.ACCOUNT_ACC_FIELD.name = "acc"
_M.ACCOUNT_ACC_FIELD.full_name = ".Account.acc"
_M.ACCOUNT_ACC_FIELD.number = 2
_M.ACCOUNT_ACC_FIELD.index = 1
_M.ACCOUNT_ACC_FIELD.label = 2
_M.ACCOUNT_ACC_FIELD.has_default_value = false
_M.ACCOUNT_ACC_FIELD.default_value = ""
_M.ACCOUNT_ACC_FIELD.type = 9
_M.ACCOUNT_ACC_FIELD.cpp_type = 9

_M.ACCOUNT_PWD_FIELD.name = "pwd"
_M.ACCOUNT_PWD_FIELD.full_name = ".Account.pwd"
_M.ACCOUNT_PWD_FIELD.number = 3
_M.ACCOUNT_PWD_FIELD.index = 2
_M.ACCOUNT_PWD_FIELD.label = 2
_M.ACCOUNT_PWD_FIELD.has_default_value = false
_M.ACCOUNT_PWD_FIELD.default_value = ""
_M.ACCOUNT_PWD_FIELD.type = 9
_M.ACCOUNT_PWD_FIELD.cpp_type = 9

_M.ACCOUNT_NICKNAME_FIELD.name = "nickname"
_M.ACCOUNT_NICKNAME_FIELD.full_name = ".Account.nickname"
_M.ACCOUNT_NICKNAME_FIELD.number = 4
_M.ACCOUNT_NICKNAME_FIELD.index = 3
_M.ACCOUNT_NICKNAME_FIELD.label = 2
_M.ACCOUNT_NICKNAME_FIELD.has_default_value = false
_M.ACCOUNT_NICKNAME_FIELD.default_value = ""
_M.ACCOUNT_NICKNAME_FIELD.type = 9
_M.ACCOUNT_NICKNAME_FIELD.cpp_type = 9

_M.ACCOUNT_ROOMID_FIELD.name = "roomid"
_M.ACCOUNT_ROOMID_FIELD.full_name = ".Account.roomid"
_M.ACCOUNT_ROOMID_FIELD.number = 5
_M.ACCOUNT_ROOMID_FIELD.index = 4
_M.ACCOUNT_ROOMID_FIELD.label = 2
_M.ACCOUNT_ROOMID_FIELD.has_default_value = false
_M.ACCOUNT_ROOMID_FIELD.default_value = 0
_M.ACCOUNT_ROOMID_FIELD.type = 5
_M.ACCOUNT_ROOMID_FIELD.cpp_type = 1

_M.ACCOUNT_ICO_FIELD.name = "ico"
_M.ACCOUNT_ICO_FIELD.full_name = ".Account.ico"
_M.ACCOUNT_ICO_FIELD.number = 6
_M.ACCOUNT_ICO_FIELD.index = 5
_M.ACCOUNT_ICO_FIELD.label = 2
_M.ACCOUNT_ICO_FIELD.has_default_value = false
_M.ACCOUNT_ICO_FIELD.default_value = ""
_M.ACCOUNT_ICO_FIELD.type = 12
_M.ACCOUNT_ICO_FIELD.cpp_type = 9

_M.ACCOUNT.name = "Account"
_M.ACCOUNT.full_name = ".Account"
_M.ACCOUNT.nested_types = {}
_M.ACCOUNT.enum_types = {}
_M.ACCOUNT.fields = {_M.ACCOUNT_ID_FIELD, _M.ACCOUNT_ACC_FIELD, _M.ACCOUNT_PWD_FIELD, _M.ACCOUNT_NICKNAME_FIELD, _M.ACCOUNT_ROOMID_FIELD, _M.ACCOUNT_ICO_FIELD}
_M.ACCOUNT.is_extendable = false
_M.ACCOUNT.extensions = {}

_M.Account = protobuf.Message(_M.ACCOUNT)

return _M