--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Framework.Net.Protobuf.protobuf"
local _M = {}

_M.USER = protobuf.Descriptor();
_M.USER_ID_FIELD = protobuf.FieldDescriptor();
_M.USER_NAME_FIELD = protobuf.FieldDescriptor();
_M.USER_SEX_FIELD = protobuf.FieldDescriptor();
_M.USER_GOLD_FIELD = protobuf.FieldDescriptor();

_M.USER_ID_FIELD.name = "id"
_M.USER_ID_FIELD.full_name = ".User.id"
_M.USER_ID_FIELD.number = 1
_M.USER_ID_FIELD.index = 0
_M.USER_ID_FIELD.label = 2
_M.USER_ID_FIELD.has_default_value = false
_M.USER_ID_FIELD.default_value = 0
_M.USER_ID_FIELD.type = 5
_M.USER_ID_FIELD.cpp_type = 1

_M.USER_NAME_FIELD.name = "name"
_M.USER_NAME_FIELD.full_name = ".User.name"
_M.USER_NAME_FIELD.number = 2
_M.USER_NAME_FIELD.index = 1
_M.USER_NAME_FIELD.label = 2
_M.USER_NAME_FIELD.has_default_value = false
_M.USER_NAME_FIELD.default_value = ""
_M.USER_NAME_FIELD.type = 9
_M.USER_NAME_FIELD.cpp_type = 9

_M.USER_SEX_FIELD.name = "sex"
_M.USER_SEX_FIELD.full_name = ".User.sex"
_M.USER_SEX_FIELD.number = 3
_M.USER_SEX_FIELD.index = 2
_M.USER_SEX_FIELD.label = 2
_M.USER_SEX_FIELD.has_default_value = false
_M.USER_SEX_FIELD.default_value = 0
_M.USER_SEX_FIELD.type = 5
_M.USER_SEX_FIELD.cpp_type = 1

_M.USER_GOLD_FIELD.name = "gold"
_M.USER_GOLD_FIELD.full_name = ".User.gold"
_M.USER_GOLD_FIELD.number = 4
_M.USER_GOLD_FIELD.index = 3
_M.USER_GOLD_FIELD.label = 2
_M.USER_GOLD_FIELD.has_default_value = false
_M.USER_GOLD_FIELD.default_value = 0
_M.USER_GOLD_FIELD.type = 5
_M.USER_GOLD_FIELD.cpp_type = 1

_M.USER.name = "User"
_M.USER.full_name = ".User"
_M.USER.nested_types = {}
_M.USER.enum_types = {}
_M.USER.fields = {_M.USER_ID_FIELD, _M.USER_NAME_FIELD, _M.USER_SEX_FIELD, _M.USER_GOLD_FIELD}
_M.USER.is_extendable = false
_M.USER.extensions = {}

_M.User = protobuf.Message(_M.USER)

return _M