--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Framework.Net.Protobuf.protobuf"
local _M = {}

_M.USER = protobuf.Descriptor();
_M.USER_ID_FIELD = protobuf.FieldDescriptor();
_M.USER_NAME_FIELD = protobuf.FieldDescriptor();
_M.USER_SEX_FIELD = protobuf.FieldDescriptor();
_M.USER_GOLD_FIELD = protobuf.FieldDescriptor();
_M.GAMEPLAYER = protobuf.Descriptor();
_M.GAMEPLAYER_SEATID_FIELD = protobuf.FieldDescriptor();
_M.GAMEPLAYER_STATE_FIELD = protobuf.FieldDescriptor();
_M.GAMEPLAYER_USER_FIELD = protobuf.FieldDescriptor();
_M.GAMESEATEDUPLAYERS = protobuf.Descriptor();
_M.GAMESEATEDUPLAYERS_ROOMID_FIELD = protobuf.FieldDescriptor();
_M.GAMESEATEDUPLAYERS_PLAYERS_FIELD = protobuf.FieldDescriptor();

_M.USER_ID_FIELD.name = "id"
_M.USER_ID_FIELD.full_name = ".User.id"
_M.USER_ID_FIELD.number = 1
_M.USER_ID_FIELD.index = 0
_M.USER_ID_FIELD.label = 2
_M.USER_ID_FIELD.has_default_value = false
_M.USER_ID_FIELD.default_value = 0
_M.USER_ID_FIELD.type = 5
_M.USER_ID_FIELD.cpp_type = 1

_M.USER_NAME_FIELD.name = "name"
_M.USER_NAME_FIELD.full_name = ".User.name"
_M.USER_NAME_FIELD.number = 2
_M.USER_NAME_FIELD.index = 1
_M.USER_NAME_FIELD.label = 2
_M.USER_NAME_FIELD.has_default_value = false
_M.USER_NAME_FIELD.default_value = ""
_M.USER_NAME_FIELD.type = 9
_M.USER_NAME_FIELD.cpp_type = 9

_M.USER_SEX_FIELD.name = "sex"
_M.USER_SEX_FIELD.full_name = ".User.sex"
_M.USER_SEX_FIELD.number = 3
_M.USER_SEX_FIELD.index = 2
_M.USER_SEX_FIELD.label = 2
_M.USER_SEX_FIELD.has_default_value = false
_M.USER_SEX_FIELD.default_value = 0
_M.USER_SEX_FIELD.type = 5
_M.USER_SEX_FIELD.cpp_type = 1

_M.USER_GOLD_FIELD.name = "gold"
_M.USER_GOLD_FIELD.full_name = ".User.gold"
_M.USER_GOLD_FIELD.number = 4
_M.USER_GOLD_FIELD.index = 3
_M.USER_GOLD_FIELD.label = 2
_M.USER_GOLD_FIELD.has_default_value = false
_M.USER_GOLD_FIELD.default_value = 0
_M.USER_GOLD_FIELD.type = 5
_M.USER_GOLD_FIELD.cpp_type = 1

_M.USER.name = "User"
_M.USER.full_name = ".User"
_M.USER.nested_types = {}
_M.USER.enum_types = {}
_M.USER.fields = {_M.USER_ID_FIELD, _M.USER_NAME_FIELD, _M.USER_SEX_FIELD, _M.USER_GOLD_FIELD}
_M.USER.is_extendable = false
_M.USER.extensions = {}
_M.GAMEPLAYER_SEATID_FIELD.name = "seatid"
_M.GAMEPLAYER_SEATID_FIELD.full_name = ".GamePlayer.seatid"
_M.GAMEPLAYER_SEATID_FIELD.number = 1
_M.GAMEPLAYER_SEATID_FIELD.index = 0
_M.GAMEPLAYER_SEATID_FIELD.label = 2
_M.GAMEPLAYER_SEATID_FIELD.has_default_value = false
_M.GAMEPLAYER_SEATID_FIELD.default_value = 0
_M.GAMEPLAYER_SEATID_FIELD.type = 5
_M.GAMEPLAYER_SEATID_FIELD.cpp_type = 1

_M.GAMEPLAYER_STATE_FIELD.name = "state"
_M.GAMEPLAYER_STATE_FIELD.full_name = ".GamePlayer.state"
_M.GAMEPLAYER_STATE_FIELD.number = 2
_M.GAMEPLAYER_STATE_FIELD.index = 1
_M.GAMEPLAYER_STATE_FIELD.label = 2
_M.GAMEPLAYER_STATE_FIELD.has_default_value = false
_M.GAMEPLAYER_STATE_FIELD.default_value = 0
_M.GAMEPLAYER_STATE_FIELD.type = 5
_M.GAMEPLAYER_STATE_FIELD.cpp_type = 1

_M.GAMEPLAYER_USER_FIELD.name = "user"
_M.GAMEPLAYER_USER_FIELD.full_name = ".GamePlayer.user"
_M.GAMEPLAYER_USER_FIELD.number = 3
_M.GAMEPLAYER_USER_FIELD.index = 2
_M.GAMEPLAYER_USER_FIELD.label = 2
_M.GAMEPLAYER_USER_FIELD.has_default_value = false
_M.GAMEPLAYER_USER_FIELD.default_value = nil
_M.GAMEPLAYER_USER_FIELD.message_type = _M.USER
_M.GAMEPLAYER_USER_FIELD.type = 11
_M.GAMEPLAYER_USER_FIELD.cpp_type = 10

_M.GAMEPLAYER.name = "GamePlayer"
_M.GAMEPLAYER.full_name = ".GamePlayer"
_M.GAMEPLAYER.nested_types = {}
_M.GAMEPLAYER.enum_types = {}
_M.GAMEPLAYER.fields = {_M.GAMEPLAYER_SEATID_FIELD, _M.GAMEPLAYER_STATE_FIELD, _M.GAMEPLAYER_USER_FIELD}
_M.GAMEPLAYER.is_extendable = false
_M.GAMEPLAYER.extensions = {}
_M.GAMESEATEDUPLAYERS_ROOMID_FIELD.name = "roomid"
_M.GAMESEATEDUPLAYERS_ROOMID_FIELD.full_name = ".GameSeatedUPlayers.roomid"
_M.GAMESEATEDUPLAYERS_ROOMID_FIELD.number = 1
_M.GAMESEATEDUPLAYERS_ROOMID_FIELD.index = 0
_M.GAMESEATEDUPLAYERS_ROOMID_FIELD.label = 2
_M.GAMESEATEDUPLAYERS_ROOMID_FIELD.has_default_value = false
_M.GAMESEATEDUPLAYERS_ROOMID_FIELD.default_value = 0
_M.GAMESEATEDUPLAYERS_ROOMID_FIELD.type = 5
_M.GAMESEATEDUPLAYERS_ROOMID_FIELD.cpp_type = 1

_M.GAMESEATEDUPLAYERS_PLAYERS_FIELD.name = "players"
_M.GAMESEATEDUPLAYERS_PLAYERS_FIELD.full_name = ".GameSeatedUPlayers.players"
_M.GAMESEATEDUPLAYERS_PLAYERS_FIELD.number = 2
_M.GAMESEATEDUPLAYERS_PLAYERS_FIELD.index = 1
_M.GAMESEATEDUPLAYERS_PLAYERS_FIELD.label = 3
_M.GAMESEATEDUPLAYERS_PLAYERS_FIELD.has_default_value = false
_M.GAMESEATEDUPLAYERS_PLAYERS_FIELD.default_value = {}
_M.GAMESEATEDUPLAYERS_PLAYERS_FIELD.message_type = _M.GAMEPLAYER
_M.GAMESEATEDUPLAYERS_PLAYERS_FIELD.type = 11
_M.GAMESEATEDUPLAYERS_PLAYERS_FIELD.cpp_type = 10

_M.GAMESEATEDUPLAYERS.name = "GameSeatedUPlayers"
_M.GAMESEATEDUPLAYERS.full_name = ".GameSeatedUPlayers"
_M.GAMESEATEDUPLAYERS.nested_types = {}
_M.GAMESEATEDUPLAYERS.enum_types = {}
_M.GAMESEATEDUPLAYERS.fields = {_M.GAMESEATEDUPLAYERS_ROOMID_FIELD, _M.GAMESEATEDUPLAYERS_PLAYERS_FIELD}
_M.GAMESEATEDUPLAYERS.is_extendable = false
_M.GAMESEATEDUPLAYERS.extensions = {}

_M.GamePlayer = protobuf.Message(_M.GAMEPLAYER)
_M.GameSeatedUPlayers = protobuf.Message(_M.GAMESEATEDUPLAYERS)
_M.User = protobuf.Message(_M.USER)

return _M